sudo: required

services:
  - docker

language: generic

before_install:
  - docker build -t emiresen/tennisleague-react -f Dockerfile.dev .


# script:
  # -docker run -e CI=true emiresen/tennisleague-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "tennisleague-react"
  env: "tennisleague-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-026090522719"
  bucket_path: "tennisleague-react"
  on:
    branch: main
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key 
