sudo: required

services:
  - docker

before_install:
  - docker build -t emiresen/tennisleague-react -f Dockerfile.dev .
  

# script:
  # -docker run -e CI=true emiresen/tennisleague-react npm run test
